sudo: required
services:
  - docker

before_install:
  - docker build -t burakcakan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true burakcakan/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "copy_from_S3"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"