sudo: required
services:
  - docker

before_install:
  - docker build -t burakcakan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true burakcakan/docker-react npm run test

language: generic